### ISSUE TITLE
Missing jQuery selector in javascript version

### ISSUE THREAD

**Issue by CaptainQuirk** [maccman/spine.todos#5]
The TaskApp::create() function should be like this : 

create : function(e){
      e.preventDefault();
      console.log ( this ) ;
      Task.create({name:this.$("input").val()});
      this.$("input").val("");
    } ,

rather than 

create : function(e){
      e.preventDefault();
      console.log ( this ) ;
      Task.create({name:this.input.val()});
      this.input.val("");
    } ,

where the jQuery selector is missing causing an error to be thrown when trying to access undefined "input" property of this

**Comment by maccman** [comment]
Nope, input is set by the 'elements' hash - ping me on irc about this.
